[project]
name = "twmr"
version = "0.1.0"
description = "MuJoCo Playground environment for training our transformable wheel mobile robot."
readme = "README.md"
authors = [
    { name = "anthonyjclark", email = "anthonyjclark@gmail.com" }
]
requires-python = ">=3.11"
dependencies = []

[project.scripts]
twmr = "twmr:main"

[build-system]
requires = ["uv_build>=0.9.18,<0.10.0"]
build-backend = "uv_build"
